version: '3.8'
services:
  db:
    image: postgres
    container_name: newsfeed-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newsfeed
  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: cache
    environment:
      - ADDR=cache:6379
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASSWORD}
    volumes: 
      - cache:/data
  main-app-newsfeed:
    container_name: main-app-newsfeed
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=newsfeed-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
volumes:
  cache:
    driver: local
  main-app:
    driver: local